services:
  backend:
    build: ./todolist/backend
    ports:
      - "3000:3000"
    networks:
      - todolist-network
    environment:
      MONGO_URI: mongodb+srv://quin:quin@cluster0.cdr4r.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build: ./todolist/frontend
    ports:
      - "5173:5173"
    networks:
      - todolist-network
    environment:
      VITE_BACKEND_URL: http://backend:3000
    depends_on:
      - backend

  networks:
    todolist-network:
      driver: bridge